# Generated by Django 3.2.13 on 2022-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='title',
            field=models.CharField(help_text='Введите марку авто', max_length=200, unique=True, verbose_name='Марка'),
        ),
    ]
